// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdwmTmRA3EvYlnxaG4nclkJl1eoJ5r5p4',
    appId: '1:233249280251:web:4eae4606855ee301e9605e',
    messagingSenderId: '233249280251',
    projectId: 'dristi-1046',
    authDomain: 'dristi-1046.firebaseapp.com',
    storageBucket: 'dristi-1046.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13g5OdwGZFWK0wdgkK62O5vRagIQdcSs',
    appId: '1:233249280251:android:ccaa17d86ac5069ce9605e',
    messagingSenderId: '233249280251',
    projectId: 'dristi-1046',
    storageBucket: 'dristi-1046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQgKXZKyp0vojyAyYMAnCYsFwYKnGAVM',
    appId: '1:233249280251:ios:73f1c655ab041086e9605e',
    messagingSenderId: '233249280251',
    projectId: 'dristi-1046',
    storageBucket: 'dristi-1046.appspot.com',
    iosBundleId: 'com.example.dristi',
  );
}
