name: dristi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  flutter_riverpod: 2.5.1
  logger: 2.3.0
  flutter_screenutil: 5.9.1
  flutter_svg: 2.0.10+1
  carousel_slider: 4.2.1
  equatable: 2.0.5
  dio: 5.4.3+1
  hive_flutter: 1.1.0
  get_it: 7.7.0
  flutter_localization: 0.2.0
  intl: 0.19.0
  shimmer: 3.0.0
  go_router: 14.1.3
  cached_network_image: 3.3.1
  connectivity_plus: 6.0.3
  webview_flutter: 4.8.0
  url_launcher: 6.3.0
  photo_view: 0.15.0
  flutter_staggered_grid_view: 0.7.0
  gal: 2.3.0
  rive_animated_icon: 2.0.0

# Run fvm flutter gen-l10n / flutter gen-l10n if Localization error

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 5.1.0
  flutter_lints: 2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/destination_items/
    - assets/images/items/
    - assets/images/on_boarding/
    - assets/json/

  fonts:
    - family: Nova
      fonts:
        - asset: assets/fonts/Nova-Square-Regular.ttf
          weight: 700
    - family: Vibes
      fonts:
        - asset: assets/fonts/Great-Vibes-Regular.ttf
          weight: 700

